#! /bin/sh

name=bootloader
skip_pkg_check=yes
version=0
revision=1
source_dir=bootloader
imagedeps="build-essential"
hostdeps="gcc-bootstrap"

configure() {
    cmake_configure
}

build() {
    cmake --build . -j"${parallelism}"
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

    post_package_strip
}
