#! /bin/sh

name=coreutils
version=9.8
tarball_url="https://ftpmirror.gnu.org/gnu/coreutils/coreutils-${version}.tar.xz"
tarball_blake2b="a93e26c8dda875b11541808d82ff8d6537f521b9c44e2a9959ee8f452823a4df5aed2793ac32766e2d3f832606d7190f7f53ea5870419f585aa66429a9626d98"
revision=1
imagedeps="build-essential"
source_hostdeps="autoconf"
hostdeps="gcc"
deps="core-libs"

prepare() {
    for name in config.guess config.sub; do
        cp -p "/usr/local/share/autoconf/build-aux/$name" build-aux
    done
}

configure() {
    autotools_configure \
        --enable-no-install-program=mkfifo,runcon,chroot,uptime,kill
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

    post_package_strip
}
