#! /bin/sh

name=file
version=5.46
tarball_url="https://astron.com/pub/file/file-${version}.tar.gz"
tarball_blake2b="2b1df136f01c253cc490b483c644403da0674692ef97ef9e1239878328cfb8ce2bc418c14626145719c69acab00d56b63b5340a2b56c276c996b1e6ad1bfe9b6"
revision=1
imagedeps="build-essential"
source_hostdeps="autoconf automake libtool pkg-config"
hostdeps="gcc pkg-config file"
deps="core-libs bzip2 xz zlib zstd"

prepare() {
    autotools_regen
}

configure() {
    autotools_configure
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

    post_package_strip
}
