#! /bin/sh

name=linux-headers
skip_pkg_check=yes
from_source=linux
revision=1
imagedeps="build-essential rsync"

configure() {
    cp -pr "${source_dir}/." .
}

package() {
    make -j"${parallelism}"                     \
        ARCH="${JINX_ARCH}"                     \
        CROSS_COMPILE="${OS_TRIPLET}-"          \
        INSTALL_HDR_PATH="${dest_dir}${prefix}" \
        headers_install

    post_package_strip
}
