#! /bin/sh

name=linux
version=6.16.0
git_url="https://github.com/monkuous/xrlinux.git"
commit="8a63f7825fadff4cc73193a6ac10bf2dde47dd1c"
revision=1
source_imagedeps="build-essential bc"
source_hostdeps="gcc-bootstrap"
imagedeps="build-essential bc"
hostdeps="gcc-bootstrap"

prepare() {
    make -j"${parallelism}" ARCH="${JINX_ARCH}" CROSS_COMPILE="${OS_TRIPLET}-" mrproper
    cp -p "${base_dir}/build-support/kernel-config.${JINX_ARCH}" .config
    make -j"${parallelism}" ARCH="${JINX_ARCH}" CROSS_COMPILE="${OS_TRIPLET}-" olddefconfig
}

configure() {
    cp -pr "${source_dir}/." .
}

build() {
    make -j"${parallelism}" ARCH="${JINX_ARCH}" CROSS_COMPILE="${OS_TRIPLET}-"
}

package() {
    mkdir -p "${dest_dir}/boot"

    case "${JINX_ARCH}" in
    xr17032)    cp -p arch/xr17032/boot/Image "${dest_dir}/boot/vmlinux" ;;
    esac

    make -j"${parallelism}"                     \
        ARCH="${JINX_ARCH}"                     \
        CROSS_COMPILE="${OS_TRIPLET}-"          \
        INSTALL_MOD_PATH="${dest_dir}${prefix}" \
        INSTALL_MOD_STRIP=1                     \
        modules_install

    post_package_strip
}
