#! /bin/sh

JINX_MAJOR_VER=0.6

HOST_CFLAGS="-O2 -pipe"
HOST_CXXFLAGS="${HOST_CFLAGS}"
HOST_LDFLAGS=""

TARGET_CFLAGS="$HOST_CFLAGS"
TARGET_CXXFLAGS="$HOST_CXXFLAGS"
TARGET_LDFLAGS="$HOST_LDFLAGS"

OS_TRIPLET="${JINX_ARCH}"-unknown-linux-gnu

post_package_strip() {
    if [ -z "$strip_command" ]; then
        strip_command="${OS_TRIPLET}-strip"
    fi

    for f in $(find "${dest_dir}" ! -name "*.o"); do
        if file "$f" | grep 'not stripped' >/dev/null; then
            echo "* stripping '$f'..."
            stripped_file="$(mktemp)"
            ${strip_command} "$f" -o "$stripped_file"
            chmod --reference="$f" "$stripped_file"
            mv -f "$stripped_file" "$f"
        fi
    done
}

autotools_regen() {
    ACLOCAL_INCLUDE=""
    if [ -d "${sysroot_dir}/usr/share/aclocal" ]; then
        ACLOCAL_INCLUDE="-Isysroot_dir/usr/share/aclocal"
    fi

    find . '(' -name configure.ac -o -name configure.in ')' -type f -print0 \
            | sort -z | xargs -0 autoreconf -fvi "$@" $ACLOCAL_INCLUDE
}

autotools_configure() {
        CFLAGS="$TARGET_CFLAGS"                 \
        CXXFLAGS="$TARGET_CXXFLAGS"             \
        LDFLAGS="$TARGET_LDFLAGS"               \
    "${source_dir}/configure"                   \
        --host="${OS_TRIPLET}"                  \
        --with-sysroot="${sysroot_dir}"         \
        --prefix="${prefix}"                    \
        --sysconfdir=/etc                       \
        --localstatedir=/var                    \
        --bindir="${prefix}/bin"                \
        --sbindir="${prefix}/bin"               \
        --libdir="${prefix}/lib"                \
        --disable-werror                        \
        --disable-static                        \
        --enable-shared                         \
        "$@"
}

cmake_configure() {
    if [ -z "${cmake_source_dir}" ]; then
        cmake_source_dir="${source_dir}"
    fi

        CFLAGS="$TARGET_CFLAGS"                 \
        CXXFLAGS="$TARGET_CXXFLAGS"             \
        LDFLAGS="$TARGET_LDFLAGS"               \
    cmake "${cmake_source_dir}"                                                             \
        -GNinja                                                                             \
        -DCMAKE_TOOLCHAIN_FILE="${base_dir}/build-support/cmake-toolchain-${JINX_ARCH}.txt" \
        -DCMAKE_INSTALL_PREFIX="${prefix}"                                                  \
        -DCMAKE_INSTALL_SYSCONFDIR=/etc                                                     \
        -DCMAKE_INSTALL_LOCALSTATEDIR=/var                                                  \
        -DCMAKE_INSTALL_LIBDIR=lib                                                          \
        -DCMAKE_INSTALL_SBINDIR=bin                                                         \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo                                                   \
        -DBUILD_SHARED_LIBS=ON                                                              \
        -DBUILD_STATIC_LIBS=OFF                                                             \
        -DENABLE_STATIC=OFF                                                                 \
        -DPKG_CONFIG_EXECUTABLE="/usr/local/bin/$OS_TRIPLET-pkg-config"                     \
        -DCMAKE_COLOR_DIAGNOSTICS=ON                                                        \
        "$@"
}

meson_configure() {
    if [ -z "${meson_source_dir}" ]; then
        meson_source_dir="${source_dir}"
    fi

        CFLAGS="$TARGET_CFLAGS"                                                 \
        CXXFLAGS="$TARGET_CXXFLAGS"                                             \
        LDFLAGS="$TARGET_LDFLAGS"                                               \
    meson setup "${meson_source_dir}"                                           \
        --cross-file="${base_dir}/build-support/meson-cross-${JINX_ARCH}.txt"   \
        --prefix="${prefix}"                                                    \
        --sysconfdir=/etc                                                       \
        --localstatedir=/var                                                    \
        --libdir=lib                                                            \
        --sbindir=bin                                                           \
        --buildtype=release                                                     \
        --wrap-mode=nodownload                                                  \
        -Ddefault_library=shared                                                \
        "$@"
}
