#! /bin/sh

name=automake
from_source=automake
revision=1
imagedeps="build-essential"
hostdeps="autoconf"

configure() {
        CFLAGS="$HOST_CFLAGS"       \
        CXXFLAGS="$HOST_CXXFLAGS"   \
        LDFLAGS="$HOST_LDFLAGS"     \
    "${source_dir}/configure"       \
        --prefix="${prefix}"
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

        strip_command=strip \
    post_package_strip
}
