#! /bin/sh

name=autoconf
from_source=autoconf
imagedeps="build-essential"
revision=1

configure() {
        CFLAGS="$HOST_CFLAGS"       \
        CXXFLAGS="$HOST_CXXFLAGS"   \
        LDFLAGS="$HOST_LDFLAGS"     \
    "${source_dir}/configure"       \
        --prefix="${prefix}"
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

        strip_command=strip \
    post_package_strip
}
