#! /bin/sh

name=binutils
from_source=binutils
revision=1
imagedeps="build-essential"
hostdeps="pkg-config"

configure() {
        CFLAGS="$HOST_CFLAGS"           \
        CXXFLAGS="$HOST_CXXFLAGS"       \
        LDFLAGS="$HOST_LDFLAGS"         \
    "${source_dir}/configure"           \
        --target="${OS_TRIPLET}"        \
        --with-sysroot="${sysroot_dir}" \
        --prefix="${prefix}"            \
        --disable-werror                \
        --disable-nls
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

        strip_command=strip \
    post_package_strip
}
