#! /bin/sh

name=file
from_source=file
revision=1
imagedeps="build-essential file"

configure() {
        CFLAGS="$HOST_CFLAGS"       \
        CXXFLAGS="$HOST_CXXFLAGS"   \
        LDFLAGS="$HOST_LDFLAGS"     \
    "${source_dir}"/configure       \
        --prefix="${prefix}"        \
        --sysconfdir=/etc           \
        --localstatedir=/var        \
        --disable-nls               \
        --disable-static
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install

        strip_command=strip \
    post_package_strip
}
