#! /bin/sh

name=gcc
from_source=gcc
revision=1
imagedeps="build-essential libgmp-dev libmpc-dev libmpfr-dev"
hostdeps="pkg-config"
hostrundeps="binutils"
deps="glibc"

configure() {
        CFLAGS="$HOST_CFLAGS"                   \
        CXXFLAGS="$HOST_CXXFLAGS"               \
        LDFLAGS="$HOST_LDFLAGS"                 \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS"      \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS"  \
    "${source_dir}"/configure                   \
        --target="${OS_TRIPLET}"                \
        --with-sysroot="${sysroot_dir}"         \
        --prefix="${prefix}"                    \
        --disable-werror                        \
        --disable-nls                           \
        --enable-languages=c,c++                \
        --enable-default-pie                    \
        --enable-shared
}

build() {
    make -j"${parallelism}"
}

package() {
    make -j"${parallelism}" DESTDIR="${dest_dir}" install
}
