#! /bin/sh

name=install-apt
from_source=install-apt
revision=1
imagedeps="build-essential"

configure() {
    cmake "${source_dir}"                   \
        -G Ninja                            \
        -DCMAKE_INSTALL_PREFIX="${prefix}"  \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo
}

build() {
    cmake --build . -j"${parallelism}"
}

package() {
    DESTDIR="${dest_dir}" cmake --install .

        strip_command=strip \
    post_package_strip
}
